#pragma once

#define LOOK_ROTATE_SPEED  300.0f
#define LOOK_MAX_ANGLE  89.5f

#define PLAYER_RUN_SPEED  10.0f
#define PLAYER_WALK_SPEED  5.0f
#define PLAYER_CROUCH_SPEED  2.0f

#define PLAYER_MAX_HEALTH  100.0f

#define PLAYER_CROUCH_SCALE  0.7f

#define MAX_SHADER_LIGHTS  8

#define FANCY_SHADER_MAX_DIR_LIGHTS  8
#define FANCY_SHADER_MAX_SPOT_LIGHTS  16
#define FANCY_SHADER_MAX_POINT_LIGHTS  32

#define STANDBY_RELOAD_WAIT_TIME  400
